### ISSUE TITLE
Garden visitors + Items in Sacks

### ISSUE THREAD

**Issue by Sandstorrm** [hannibal00212/SkyHanni#1003]
Currently some visitors will say ready when there is enough items in the Sack, others dont, also please make the visitor HUD display how many crops where collected in % for that visitor.
<img width="474" alt="Screenshot 2024-02-13 at 12 16 13 PM" src="https://github.com/hannibal002/SkyHanni/assets/105359227/a03cf055-0a4f-4e0a-ad1a-14dc86abaa68">

**Comment by lunaynx** [comment]
> Currently some visitors will say ready when there is enough items in the Sack, others dont

I already reported this on Discord. Currently it only says ready if:
- you currently have all the items needed in your inventory
- you had the items in your sacks when first talking to the visitor

> also please make the visitor HUD display how many crops where collected in % for that visitor.

The latest beta already shows how many of the needed items you have in your sacks, not a % though.

**Comment by CalMWolfs** [comment]
Thanks for the suggestion, but please in future make these on the discord. This is because all of our suggestions are kept there and as alexiayaa pointed out, I already added part of the feature you requested a few weeks ago which you would've seen if you were on the discord and kept your mod up to date.

**Comment by Sandstorrm** [comment]
Thanks. I'll be sure to join the discord and post suggestions there. This is an incredible mod and I'm really thankful for such fast response time.
