### ISSUE TITLE
Not sure if its an issue or im just dumb

### ISSUE THREAD

**Issue by Ghostly187** [hannibal00212/SkyHanni#38]
There is not option to change the location of the skymart prices
<img width="959" alt="image" src="https://user-images.githubusercontent.com/130479631/231443262-7c94e24c-5bdb-40e9-b40c-0f89b64d17c6.png">

**Comment by hannibal002** [comment]
Do you want to move a GUI element that is not always visible because it only appears in an inventory? (e.g. Copper Price or Anita Price)
You can edit these GUI elements with the GUI editor hotkey:

1. Open the '/sh' config and go to the location editor category.
2. Click on the 'Edit' button at the 'Hotkey' option.
3. Set any key on your keyboard (that you do not press accidentally) as the hotkey.
4. Open the inventory so that the GUI item you want to move appears.
5. Press the hotkey to edit the GUI item.
